from willie import module
 
@module.rule('[a-zA-z\s\.]*[\s]+iz')
@module.rule('iz$')
@module.rule('[a-zA-z\s\.]*[\s]+k')
@module.rule('k$')
@module.rule('[a-zA-z\s\.]*[\s]+txt')
@module.rule('txt$')
@module.rule('[a-zA-z\s\.]*[\s]+thx')
@module.rule('thx$')
@module.rule('[a-zA-z\s\.]*[\s]+2day')
@module.rule('2day$')
@module.rule('[a-zA-z\s\.]*[\s]+c u')
@module.rule('c u$')
@module.rule('[a-zA-z\s\.]*[\s]+tym')
@module.rule('tym$')
@module.rule('[a-zA-z\s\.]*[\s]+gr8')
@module.rule('gr8$')
@module.rule('[a-zA-z\s\.]*[\s]+r u')
@module.rule('r u$ ')
@module.rule('[a-zA-z\s\.]*[\s]+y')
@module.rule('y$')
@module.rule('[a-zA-z\s\.]*[\s]+u')
@module.rule('u$')
@module.rule('[a-zA-z\s\.]*[\s]+b')
@module.rule('b$')
@module.rule('[a-zA-z\s\.]*[\s]+2mrw')
@module.rule('2mrw$')
@module.rule('[a-zA-z\s\.]*[\s]+4get')
@module.rule('4get$')
@module.rule('[a-zA-z\s\.]*[\s]+ur')
@module.rule('ur$')
@module.rule('[a-zA-z\s\.]*[\s]+no1')
@module.rule('no1$')
@module.rule('[a-zA-z\s\.]*[\s]+sum1')
@module.rule('sum1$')
@module.rule('[a-zA-z\s\.]*[\s]+njoy')
@module.rule('njoy')
def grammarnazi(bot, trigger):
    bot.say(trigger.nick+': Please dont use SMS language.')

